---
title: '[Insert title]'
author: "Erick Calderon-Morales"
date: ''
due_date: ""
output:
  prettydoc::html_pretty:
    highlight: pygments
    theme: tactile
    toc: yes
    number_sections: no
    toc_depth: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "",
                      fig.align = 'center',
					  fig.width = 11, fig.height = 7)
```



```{r knitr, include = FALSE}

# Save figures in specific place

knitr::opts_chunk$set(autodep        = TRUE,
                      cache          = FALSE,
                      cache.comments = TRUE,

                      # Save figures as pdf ?
                      # dev = c( "png", "pdf"),

                      # Include code?
                      echo           = FALSE,

                      error          = FALSE,
                      fig.align      = "center",

                      # Path where figures are going to be store pdf single
                      # figures
                      fig.path       = paste0("./figures_exploratory", "/"),
                      fig.width      = 11,
                      fig.height     = 7,
                      message        = FALSE,
                      warning        = FALSE)
```

```{r cleanup-docs, cache = FALSE,echo = FALSE}
# save a html copy file in a specific place
# doc.files <- c(list.files(pattern = "pdf"),
#                list.files(pattern = "html"),
#                list.files(pattern = "docx"))
#
# for (file in doc.files) {
#     file.rename(file, file.path("../../[insert_folder_name]/", file))
# }
```


```{r libaries, message = FALSE, warning = FALSE, cache = FALSE}
library(dplyr)
# For Model fitting
library(lme4)
library(nlme)
library(purrr)
# For diagnostics
library(performance)
#library(see)
# For adding new columns
library(tibble)
library(MuMIn)
library(corrplot)
```

```{r}
knitr::opts_knit$set(root.dir = "~/Documents/projects/nutrients_and_water_effects_2022/stats/")
```

```{r message=FALSE, warning=FALSE}
# Load data
source("./scripts/code_join_data_full_dataset.R")
```


```{r message=FALSE, warning=FALSE}
# Load functions
# Load functions

## Inference
source("./R/functions_inference_anova_and_tukey_tables.R")

## Plots
source("./R/function_masomenos_plots.R")

```


## Models: Question 3

$$performance\sim treatment:fixer:scaled(trait)\ + initial\ height + random( 1|\ specie)$$


### Correlation Plot
```{r}
data_for_models %>%
    select(15:18, 20,21) %>%
    cor() %>%
    corrplot.mixed(., order = 'AOE')
```

### Scale preditors aka traits

```{r}
data_for_models_scaled <-
    data_for_models %>%
    select(-c(above_biomass, below_biomass, d15n, d13c, rmf, smf, lmf,
            rgr_slope, Narea_g_m2))  %>%

    #  Narea_g_m2 not included since it has a high correlation with amax
    mutate(across(c(4, 9:12), scale))
```



### Model RGR

```{r}
lme_rgr_3way <- lme(rgr ~   treatment:nfixer:amax +
                            treatment:nfixer:gs  +
                            #treatment:nfixer:wue +
                            #treatment:nfixer:pnue +

                            init_height ,
                  random = ~1 | spcode,
                  data = data_for_models_scaled)
```

```{r}
dredge(lme_rgr_3way)
```

### Model AGR

```{r}
lme_agr_3way <- lme(agr ~   treatment:nfixer:amax +
                            treatment:nfixer:gs  +
                            treatment:nfixer:wue +
                            #treatment:nfixer:pnue +

                            init_height ,
                  random = ~1 | spcode,
                  data = data_for_models_scaled)
```

```{r}
dredge(lme_agr_3way)
```

### Model Total Biomass

```{r}
lme_total_biom_3way <- lme(total_biomass ~  treatment:nfixer:amax +
                                            treatment:nfixer:gs  +
                                            treatment:nfixer:wue +
                                            treatment:nfixer:pnue +

                                            init_height,
                            random = ~1 | spcode,
                            data = data_for_models_scaled)
```

```{r}
dredge(lme_total_biom_3way)
```

## Model shoot root ratios

```{r}
lme_3way_root_shoot_ratio <- lme(root_shoot_ratio ~  treatment:nfixer:amax +
                                                        treatment:nfixer:gs  +
                                                        treatment:nfixer:wue +
                                                        treatment:nfixer:pnue +

                                                        init_height,
                            random = ~1 | spcode,
                            data = data_for_models_scaled)
```

```{r}
dredge(lme_3way_root_shoot_ratio)
```

## Bootstraps

### Total Biomass

```{r}
# Look results before bootstrap
#report::report(models_3way_q3$lme_total_biom_3way)
```


```{r}
bootstrap_ci_total_biomass <-
        bootstrap_model_ci_df(model = lme_total_biom_3way,
                              category = "all",
                              iter = 9999)
```


#### Plot Total Biomass

```{r}

colmn <- paste0("col_", 1:3)

data_total_biomass_plot <-

        bootstrap_ci_total_biomass %>%

            unite("treat_trait", col_1, col_3, sep = "-", remove = F) %>%
            mutate(across(where(is.character), as.factor)) %>%
            filter(type == "norm") %>%
            mutate(treat_trait = factor(treat_trait, levels = c("plus_water_nutrients-amax",
                                                            "plus_water_nutrients-d13c" ,
                                                            "plus_water_nutrients-gs"   ,
                                                            "plus_water_nutrients-pnue" ,
                                                            "plus_water_nutrients-wue",
                                                            "plus_water-amax" ,
                                                            "plus_water-d13c",
                                                            "plus_water-gs"  ,
                                                            "plus_water-pnue",
                                                            "plus_water-wue",
                                                            "plus_nutrients-amax",
                                                            "plus_nutrients-d13c",
                                                            "plus_nutrients-gs"  ,
                                                            "plus_nutrients-pnue",
                                                            "plus_nutrients-wue" ,
                                                            "no_additions-amax",
                                                            "no_additions-d13c",
                                                            "no_additions-gs"  ,
                                                            "no_additions-pnue",
                                                            "no_additions-wue")))
```


```{r total_biomass_plot, fig.width = 30, fig.height = 15, fig.align = 'center'}
(total_biomass_plot <-
    cleveland_plot(x = treat_trait, y = estimate,
                                     color = col_1,
                                     ci_lower = lower, ci_upper = upper,
                                     data = data_total_biomass_plot) +
        facet_wrap(.~col_2))

```


### RGR

```{r}
# Look results before bootstrap
#report::report_parameters(models_3way_q3$lme_rgr_3way)
```

```{r}
bootstrap_ci_rgr <-
        bootstrap_model_ci_df(model = lme_rgr_3way,
                              category = "all",

                                iter = 9999)

```

#### Plot RGR
```{r}
data_rgr_plot <-
    bootstrap_ci_rgr %>%
            unite("treat_trait", col_1, col_3, sep = "-", remove = F) %>%
            mutate(across(where(is.character), as.factor)) %>%
            filter(type == "norm") %>%
            mutate(treat_trait = factor(treat_trait, levels = c("plus_water_nutrients-amax",
                                                            "plus_water_nutrients-d13c" ,
                                                            "plus_water_nutrients-gs"   ,
                                                            "plus_water_nutrients-pnue" ,
                                                            "plus_water_nutrients-wue",
                                                            "plus_water-amax" ,
                                                            "plus_water-d13c",
                                                            "plus_water-gs"  ,
                                                            "plus_water-pnue",
                                                            "plus_water-wue",
                                                            "plus_nutrients-amax",
                                                            "plus_nutrients-d13c",
                                                            "plus_nutrients-gs"  ,
                                                            "plus_nutrients-pnue",
                                                            "plus_nutrients-wue" ,
                                                            "no_additions-amax",
                                                            "no_additions-d13c",
                                                            "no_additions-gs"  ,
                                                            "no_additions-pnue",
                                                            "no_additions-wue")))
```


```{r, fig.width = 30, fig.height = 15, fig.align = 'center'}
# Plot
(rgr_plot <-
    cleveland_plot(x = treat_trait, y = estimate,
                           color = col_1,
                           ci_lower = lower, ci_upper = upper,
                            data = data_rgr_plot) +
    facet_grid(.~col_2))
```


## AGR
```{r}
bootstrap_ci_agr <-
        bootstrap_model_ci_df(model = lme_agr_3way,
                              category = "all",

                                iter = 9999)
```

#### Plot AGR
```{r}
data_agr_plot <-
    bootstrap_ci_agr %>%
            unite("treat_trait", col_1, col_3, sep = "-", remove = F) %>%
            mutate(across(where(is.character), as.factor)) %>%
            filter(type == "norm") %>%
            mutate(treat_trait = factor(treat_trait, levels = c("plus_water_nutrients-amax",
                                                            "plus_water_nutrients-d13c" ,
                                                            "plus_water_nutrients-gs"   ,
                                                            "plus_water_nutrients-pnue" ,
                                                            "plus_water_nutrients-wue",
                                                            "plus_water-amax" ,
                                                            "plus_water-d13c",
                                                            "plus_water-gs"  ,
                                                            "plus_water-pnue",
                                                            "plus_water-wue",
                                                            "plus_nutrients-amax",
                                                            "plus_nutrients-d13c",
                                                            "plus_nutrients-gs"  ,
                                                            "plus_nutrients-pnue",
                                                            "plus_nutrients-wue" ,
                                                            "no_additions-amax",
                                                            "no_additions-d13c",
                                                            "no_additions-gs"  ,
                                                            "no_additions-pnue",
                                                            "no_additions-wue")))
```


```{r, fig.width = 30, fig.height = 15, fig.align = 'center'}
# Plot
(agr_plot <-
    cleveland_plot(x = treat_trait, y = estimate,
                           color = col_1,
                           ci_lower = lower, ci_upper = upper,
                            data = data_agr_plot) +
    facet_grid(.~col_2))
```



## Root to shoot ratio

```{r}
bootstrap_ci_ratio <-
        bootstrap_model_ci_df(model = lme_3way_root_shoot_ratio,
                              category = "all",
                                iter = 9999)
```


#### Plot Root-Shoot Ratio

```{r}
data_ratio_plot <-
    bootstrap_ci_ratio %>%
            unite("treat_trait", col_1, col_3, sep = "-", remove = F) %>%
            mutate(across(where(is.character), as.factor)) %>%
            filter(type == "norm") %>%
            mutate(treat_trait = factor(treat_trait, levels = c("plus_water_nutrients-amax",
                                                            "plus_water_nutrients-d13c" ,
                                                            "plus_water_nutrients-gs"   ,
                                                            "plus_water_nutrients-pnue" ,
                                                            "plus_water_nutrients-wue",
                                                            "plus_water-amax" ,
                                                            "plus_water-d13c",
                                                            "plus_water-gs"  ,
                                                            "plus_water-pnue",
                                                            "plus_water-wue",
                                                            "plus_nutrients-amax",
                                                            "plus_nutrients-d13c",
                                                            "plus_nutrients-gs"  ,
                                                            "plus_nutrients-pnue",
                                                            "plus_nutrients-wue" ,
                                                            "no_additions-amax",
                                                            "no_additions-d13c",
                                                            "no_additions-gs"  ,
                                                            "no_additions-pnue",
                                                            "no_additions-wue")))
```

```{r, fig.width = 30, fig.height = 15, fig.align = 'center'}
# Plot
(ratio_plot <-
    cleveland_plot(x = treat_trait, y = estimate,
                           color = col_1,
                           ci_lower = lower, ci_upper = upper,
                            data = data_ratio_plot) +
    facet_grid(.~col_2))
```

