---
title: 'Model inference Q1'
author: "Erick Calderon-Morales"
date: ''
due_date: ""
output:
  prettydoc::html_pretty:
    highlight: pygments
    theme: tactile
    toc: yes
    number_sections: no
    toc_depth: 1
---

```{r, setup, include=FALSE}
# Set knit directory
knitr::opts_knit$set(root.dir = "~/Documents/projects/nutrients_and_water_effects_2022/stats/")
```


```{r knitr, include = FALSE}

# Save figures in specific place

knitr::opts_chunk$set(autodep        = TRUE,
                      cache          = FALSE,
                      cache.comments = TRUE,

                      # Save figures as pdf ?
                      # dev = c( "png", "pdf"),

                      # Include code?
                      echo           = FALSE,

                      error          = FALSE,
                      fig.align      = "center",

                      # Path where figures are going to be store pdf single
                      # figures
                      fig.path       = paste0("./figures_inference", "/"),
                      fig.width      = 11,
                      fig.height     = 7,
                      message        = FALSE,
                      warning        = FALSE)
```

```{r cleanup-docs, cache = FALSE,echo = FALSE}
# save a html copy file in a specific place
# doc.files <- c(list.files(pattern = "pdf"),
#                list.files(pattern = "html"),
#                list.files(pattern = "docx"))
#
# for (file in doc.files) {
#     file.rename(file, file.path("../../[insert_folder_name]/", file))
# }
```


```{r libaries, message = FALSE, warning = FALSE, cache = FALSE}
library(dplyr)
# For tables appearance
library(reactablefmtr)
# For cleaning colnames
library(janitor)
# For add column function
library(tibble)
library(purrr)
library(performance)
# For bootstrap confidence intervals
library(lmeresampler)
library(nlme)
library(lme4)
# For model comparison
library(MuMIn)
# For get preditions
library(modelr)
# For reporting results
library(report)
library(emmeans)
```

# Load functions and data

```{r message=FALSE, warning=FALSE}
# Load dataset for adding predictions
source("./scripts/code_join_data_full_dataset.R")
```

```{r message=FALSE, warning=FALSE}
# Load functions

## Inference
source("./R/functions_inference_anova_and_tukey_tables.R")

## Plots
source("./R/function_masomenos_plots.R")
```


__Q2: How does increased nutrient and/or water availability influence seedling
water- and nutrient-use traits and the relationships with N-fixing bacteria?__

# Load models

```{r}
models_q2 <- readRDS("./processed_data/models_q2.RData")
model_nodule_count <- readRDS("./processed_data/model_nodule_log.RData")
```


```{r}
names(models_q2)
```

```{r echo=FALSE}
# Step done for getting predictions from models for Q2
data_for_models <-
    data_for_models %>%

        rownames_to_column("id") %>%

        # Remove unused variables
        dplyr::select(id, spcode, treatment, nfixer, init_height)
```

```{r}
# Step done for getting predictions from nodule models
source("./scripts/code_clean_data_nodules.R")

data_pred_nodules <-
     data_nodules_cleaned %>%

         # add id to rownames for keep track of the rows
         dplyr::select(c("id", "spcode", "treatment", "init_height"))

```

# Traits

## ANOVAs

```{r}
models_q2 %>%

    # Remove traits and mass fractions models
    anova_table_tidy(., model_list = T)
```


## Tuckey comparisons

### Models with significant interaction

```{r}
models_q2 %>%

    purrr::list_modify("gs" = NULL, "pnue_log" = NULL, "nitrogen_log" = NULL) %>%

    tukey_table_tidy(., model_list = T, formula = "treatment|nfixer")
```

```{r}
tukey_table_tidy(models_q2$amax, single_model = TRUE, formula = "treatment|nfixer")
```

### Models with signifcant treatment effect

```{r message=FALSE, warning=FALSE}
models_q2 %>%

    # Remove performance variables
    purrr::list_modify("amax" = NULL,  "wue_log" = NULL) %>%

    tukey_table_tidy(., model_list = T, formula = "treatment")
```


### Models with signifcant nfixer effect

```{r}
models_q2 %>%

    # Remove performance variables
    purrr::list_modify("amax" = NULL, "wue_log" = NULL, "pnue_log" = NULL) %>%

    tukey_table_tidy(., model_list = T, formula = "nfixer")
```
