---
title: "Model Validation Delete"
output: html_document
---
ˆ
```{r}
library(dplyr)
# For Model fitting
library(lme4)
library(purrr)
# For diagnostics
library(performance)
# For adding new columns
library(tibble)
library(caret)
```

```{r}
# Load data
sys.source("./scripts/code_join_data_full_dataset.R", envir = knitr::knit_global())
```

```{r}
# Load functions
## Models
sys.source("./R/functions_models.R", envir = knitr::knit_global())
```


```{r}
data_for_models_transformed <-
     data_for_models %>% 
         
        mutate(
#             # Plant's performance
#             total_biomass_sqrt = sqrt(total_biomass),
#             above_biomass_sqrt = sqrt(above_biomass),
#             below_biomass_log = log(below_biomass),
#             agr_log = log(agr),
#             
#             # NO TRANSFORMATION variable already in log-log
#             rgr = rgr,
#             
#             # NO TRANSFORMATION variable already in log-log
#             rgr_slope = rgr_slope,
#           
#             # Traits
             amax_log = log(amax),
             gs_sqrt = sqrt(gs),
             wue_log = log(wue),
#             
#             # d13 and d15 where not transformed because the data has negative values
             pnue_log = log(data_for_models$pnue),
#           
#             # Covariate
             init_height = log(init_height))  %>% 
            
        # Remove original variables (non-transformed)
         dplyr::select(spcode, treatment, nfixer, init_height, everything(),
                -c(8,10,11:13,16))    
```

# Models: Questions 1 and 2

```{r}
# Take response variables' names 
response_vars_q1_q2 <- 
    set_names(names(data_for_models_transformed)[5:(ncol(data_for_models_transformed))])
```

```{r}
#data_for_models_transformed[data_for_models_transformed$id == 48,]
models_list_q1_q2 <- map(response_vars_q1_q2, ~ mixed_model_1(response = .x, 
                                                              data = data_for_models_transformed))
```


# Models Nodule count

```{r}
# Load data
# This step was done like this because I am working with a subset of the data
# source cleaned data
source("./scripts/code_clean_data_nodules.R")

# Delete unused variables
data_nodules_cleaned <-
    data_nodules_cleaned %>%
        
        # add id to rownames for keep track of the rows
        column_to_rownames("id") %>% 
        dplyr::select(spcode,treatment, everything())
```

```{r}
lmer_gaussian <- lmer(number_of_root_nodulation ~ treatment + init_height + 
                           (1 |spcode),
                       data = data_nodules_cleaned)
```

```{r}
lmer_gaussian_log <-  lmer(log(number_of_root_nodulation) ~ treatment + init_height + 
                           (1 |spcode),
                       data = data_nodules_cleaned)
```

```{r}
glmer_poisson <-  glmer(number_of_root_nodulation ~ treatment + init_height + 
                           (1 |spcode), family = "poisson",
                       data = data_nodules_cleaned)
```

```{r}
models_list_nodule_count <- list(lmer_gaussian, lmer_gaussian_log, glmer_poisson)
names(models_list_nodule_count) <- c("lmer_gaussian",
                                     "lmer_gaussian_log",
                                     "glmer_poisson")
```

# Models: Question 3

## Scale preditors

```{r}
data_for_models_transformed_scaled <-         
    data_for_models_transformed  %>% 
    
    # test for being sure that I select the traits
    #select(c(4,7,8,13:16))

        # scale only the predictors traits
        mutate(across(c(4,9:14), scale))
```


```{r}
# Select traits (x_vars)
traits_names <- 
    set_names(names(data_for_models_transformed_scaled)
                          [c(9:14)])
traits_names
```

```{r}
# Select plants performance vars (y_vars)
performance_names <- 
    set_names(names(data_for_models_transformed_scaled)[c(5:8)])

performance_names
```

```{r}
models_lmer_formulas <- model_combinations_formulas(performance_names, traits_names)

length(models_lmer_formulas)
```

```{r}
models_list_q3 <- map(models_lmer_formulas, 
                       ~ lmer(.x, data = data_for_models_transformed_scaled))
```

# Validation plots

## Collinearity

```{r}
map(models_list_q1_q2, check_collinearity)
```

```{r}
map(models_list_nodule_count, check_collinearity)
```

## bolker plots

```{r}
bolker_validation <- function(model) {
    
    
    a <- plot(model, type = c("p", "smooth"))
    
    ## heteroscedasticity
    b <-     plot(model,sqrt(abs(resid(.))) ~ fitted(.), type = c("p", "smooth"))
   
    cowplot::plot_grid(a,b,nrow = 1)
}
```

### Models for Q1 and Q2

```{r fig.height=7, fig.width=12}
map(models_list_q1_q2, bolker_validation)
```

### Models for nodule count

```{r fig.height=7, fig.width=12}
map(models_list_nodule_count, bolker_validation)
```

### Models for question 3
```{r fig.height=7, fig.width=12}
map(models_list_q3, bolker_validation)
```

## Performance package

### Models for questions 1,2


```{r fig.height=15, fig.width=16}
map(models_list_q1_q2, check_model)
```

### Models for nodule count

```{r fig.height=15, fig.width=16}
map(models_list_nodule_count, check_model)
```

### Models for question 3

```{r fig.height=15, fig.width=16}
map(models_list_q3, check_model)
```

# Save lists with the models
```{r}
saveRDS(models_list_q1_q2, file = "./processed_data/models_q1_q2.RData") 
saveRDS(models_list_q3, file = "./processed_data/models_q3_3_way_interaction.RData") 
saveRDS(models_list_nodule_count, file = "./processed_data/models_list_nodule_count.RData")
```
















